package org.weborganic.flint.test;

import java.io.File;

/**
 * A utility class for testing Flint.
 * 
 * @author Christophe Lauret (Weborganic)
 * @version 26 November 2009
 */
public class TestUtils {

  /**
   * Utility class.
   */
  private TestUtils() {
  }

  /**
   * Returns the data directory for the class being tested.
   * 
   * <p>The data directory contains test data that is permanent and required for performing tests
   * (eg. source data, etc...)
   * 
   * @param c The class being tested.
   * @return the corresponding data directory.
   */
  public static File getDataDirectory(Class<?> c) {
    File data = new File("data");
    String dir = c.getName().replace('.', File.separatorChar);
    return new File(data, dir);
  }

  /**
   * Returns the temporary directory for the class being tested.
   * 
   * <p>The temporary directory contains test data that is generated by the test from data can be deleted
   * (eg. generated index, etc...)
   * 
   * @param c The class being tested.
   * @return the corresponding data directory.
   */
  public static File getTempDirectory(Class<?> c) {
    File data = new File("tmp");
    String dir = c.getName().replace('.', File.separatorChar);
    return new File(data, dir);
  }

}
